(()=>{
const gameStyles=document.createElement('link');gameStyles.rel='stylesheet';gameStyles.href='game.css';document.head.appendChild(gameStyles);
const c=document.getElementById('game'),x=c.getContext('2d'),overlay=document.getElementById('overlay'),start=document.getElementById('start'),levelOverlay=document.getElementById('levelOverlay'),choices=document.getElementById('levelChoices'),hpEl=document.getElementById('hp'),scoreEl=document.getElementById('score'),levelEl=document.getElementById('level'),xpEl=document.getElementById('xp');
let running=false,choosing=false,last=0,spawn=0,score=0,hp=100,maxHp=100,level=1,xp=0,xpNeeded=30,keys={},mouse={x:480,y:270,down:false},enemies=[],shots=[],gems=[],audio=null;
const player={x:480,y:270,r:14,speed:220,damage:1,fireDelay:1,pickupRadius:52,multishot:1};
const enemyTypes=[{color:'#ef6b5d',r:12,speed:[76,102],hp:1,xp:10,weight:55},{color:'#a978f0',r:15,speed:[52,72],hp:2,xp:15,weight:30},{color:'#4fc0a1',r:20,speed:[32,48],hp:4,xp:24,weight:15}];
const upgrades=[{name:'신속 사격',desc:'연사 간격 15% 감소',apply:()=>player.fireDelay=Math.max(.13,player.fireDelay*.85)},{name:'강화 탄환',desc:'탄환 피해 +1',apply:()=>player.damage++},{name:'가벼운 장화',desc:'이동 속도 12% 증가',apply:()=>player.speed*=1.12},{name:'생명력',desc:'최대 체력 +25, 즉시 25 회복',apply:()=>{maxHp+=25;hp=Math.min(maxHp,hp+25)}},{name:'경험치 자석',desc:'경험치 획득 범위 45% 증가',apply:()=>player.pickupRadius*=1.45},{name:'쌍발 사격',desc:'한 번에 발사하는 탄환 +1',apply:()=>player.multishot=Math.min(4,player.multishot+1)}];
function tone(f,d=.06,v=.035,type='square'){audio??=new(window.AudioContext||window.webkitAudioContext)();const o=audio.createOscillator(),g=audio.createGain(),n=audio.currentTime;o.type=type;o.frequency.setValueAtTime(f,n);g.gain.setValueAtTime(v,n);g.gain.exponentialRampToValueAtTime(.001,n+d);o.connect(g).connect(audio.destination);o.start(n);o.stop(n+d)}
function hud(){hpEl.textContent=`체력 ${Math.max(0,Math.ceil(hp))}/${maxHp}`;scoreEl.textContent=`점수 ${score}`;levelEl.textContent=`레벨 ${level}`;xpEl.textContent=`경험치 ${xp}/${xpNeeded}`}
function reset(){score=0;hp=100;maxHp=100;level=1;xp=0;xpNeeded=30;enemies=[];shots=[];gems=[];choosing=false;Object.assign(player,{x:480,y:270,speed:220,damage:1,fireDelay:1,pickupRadius:52,multishot:1});spawn=0;shots.cool=0;hud()}
function pos(e){const r=c.getBoundingClientRect();return{x:(e.clientX-r.left)*c.width/r.width,y:(e.clientY-r.top)*c.height/r.height}}
addEventListener('keydown',e=>keys[e.key.toLowerCase()]=true);addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);c.addEventListener('mousemove',e=>Object.assign(mouse,pos(e)));c.addEventListener('mousedown',()=>mouse.down=true);addEventListener('mouseup',()=>mouse.down=false);
start.addEventListener('click',()=>{reset();audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume();tone(440,.08,.04,'sine');overlay.hidden=true;running=true;last=performance.now();requestAnimationFrame(loop)});
function enemyType(){let roll=Math.random()*100;for(const type of enemyTypes){roll-=type.weight;if(roll<=0)return type}return enemyTypes[0]}
function spawnEnemy(){const side=Math.floor(Math.random()*4),edge=side<2?Math.random()*c.width:Math.random()*c.height,type=enemyType(),difficulty=1+score/500,healthScale=1+Math.floor(score/180)*.35,speedScale=1+Math.min(score/1200,.65),health=Math.ceil(type.hp*healthScale);enemies.push({x:side===0?edge:side===2?-24:side===3?c.width+24:edge,y:side===0?-24:side===1?c.height+24:edge,r:type.r,s:(type.speed[0]+Math.random()*(type.speed[1]-type.speed[0]))*speedScale,hp:health,maxHp:health,color:type.color,xp:Math.round(type.xp*difficulty)})}
function fire(){const angle=Math.atan2(mouse.y-player.y,mouse.x-player.x),spread=.09;for(let i=0;i<player.multishot;i++){const a=angle+(i-(player.multishot-1)/2)*spread;shots.push({x:player.x,y:player.y,vx:Math.cos(a)*520,vy:Math.sin(a)*520,r:4,damage:player.damage})}shots.cool=player.fireDelay;tone(185,.035,.025)}
function gainXp(amount){xp+=amount;tone(680,.05,.025,'sine');if(xp>=xpNeeded){xp-=xpNeeded;level++;xpNeeded=Math.round(30*Math.pow(1.3,level-1));openLevelUp()}hud()}
function openLevelUp(){choosing=true;mouse.down=false;levelOverlay.hidden=false;choices.innerHTML='';[...upgrades].sort(()=>Math.random()-.5).slice(0,3).forEach(upgrade=>{const button=document.createElement('button');button.className='upgrade-choice';button.innerHTML=`<strong>${upgrade.name}</strong><span>${upgrade.desc}</span>`;button.addEventListener('click',()=>{upgrade.apply();levelOverlay.hidden=true;choosing=false;hud();tone(520,.08,.045,'sine');setTimeout(()=>tone(780,.12,.045,'sine'),70)});choices.appendChild(button)})}
function loop(t){if(!running)return;const dt=Math.min((t-last)/1000,.033);last=t;if(!choosing)update(dt);draw();if(hp<=0){running=false;overlay.hidden=false;overlay.querySelector('h1').textContent=`기록 ${score}점 · 레벨 ${level}`;overlay.querySelector('p').textContent='경험치 보석을 회수해 성장하고, 빠른 적과 튼튼한 적의 우선순위를 나눠 보세요.';start.textContent='다시 도전';tone(110,.5,.05,'sawtooth');return}requestAnimationFrame(loop)}
function update(dt){let dx=(keys.d?1:0)-(keys.a?1:0),dy=(keys.s?1:0)-(keys.w?1:0),n=Math.hypot(dx,dy)||1;player.x=Math.max(player.r,Math.min(c.width-player.r,player.x+dx/n*player.speed*dt));player.y=Math.max(player.r,Math.min(c.height-player.r,player.y+dy/n*player.speed*dt));spawn-=dt;if(spawn<=0){spawnEnemy();spawn=Math.max(.3,.95-score/1000)}shots.cool-=dt;if(mouse.down&&shots.cool<=0)fire();shots.forEach(b=>{b.x+=b.vx*dt;b.y+=b.vy*dt});shots=shots.filter(b=>b.x>-12&&b.x<c.width+12&&b.y>-12&&b.y<c.height+12);enemies.forEach(e=>{const a=Math.atan2(player.y-e.y,player.x-e.x);e.x+=Math.cos(a)*e.s*dt;e.y+=Math.sin(a)*e.s*dt;if(Math.hypot(player.x-e.x,player.y-e.y)<player.r+e.r){hp-=22*dt;hud()}});for(let i=enemies.length-1;i>=0;i--)for(let j=shots.length-1;j>=0;j--)if(Math.hypot(enemies[i].x-shots[j].x,enemies[i].y-shots[j].y)<enemies[i].r+shots[j].r){enemies[i].hp-=shots[j].damage;shots.splice(j,1);tone(105,.025,.018,'triangle');if(enemies[i].hp<=0){const e=enemies[i];gems.push({x:e.x,y:e.y,r:7,value:e.xp,pulse:Math.random()*6.28});enemies.splice(i,1);score+=10;hud();tone(260,.06,.035,'triangle')}break}gems.forEach(g=>{g.pulse+=dt*4;const d=Math.hypot(player.x-g.x,player.y-g.y);if(d<player.pickupRadius*2){const pull=Math.max(90,360*(1-d/(player.pickupRadius*2)));g.x+=(player.x-g.x)/Math.max(d,1)*pull*dt;g.y+=(player.y-g.y)/Math.max(d,1)*pull*dt}});for(let i=gems.length-1;i>=0;i--)if(Math.hypot(player.x-gems[i].x,player.y-gems[i].y)<player.r+gems[i].r+4){const value=gems[i].value;gems.splice(i,1);gainXp(value);if(choosing)break}}
function circle(px,py,r,color){x.fillStyle=color;x.beginPath();x.arc(px,py,r,0,Math.PI*2);x.fill()}
function draw(){x.fillStyle='#080c11';x.fillRect(0,0,c.width,c.height);x.strokeStyle='#172231';x.lineWidth=1;for(let i=0;i<c.width;i+=48){x.beginPath();x.moveTo(i,0);x.lineTo(i,c.height);x.stroke()}for(let i=0;i<c.height;i+=48){x.beginPath();x.moveTo(0,i);x.lineTo(c.width,i);x.stroke()}gems.forEach(g=>{x.shadowColor='#72ddff';x.shadowBlur=12;circle(g.x,g.y,g.r+Math.sin(g.pulse)*1.5,'#72ddff');x.shadowBlur=0});circle(player.x,player.y,player.r,'#f0b95b');shots.forEach(b=>circle(b.x,b.y,b.r,'#ffe4a6'));enemies.forEach(e=>{circle(e.x,e.y,e.r,e.color);if(e.maxHp>1){const w=e.r*2;x.fillStyle='#35191b';x.fillRect(e.x-e.r,e.y-e.r-8,w,3);x.fillStyle='#73df9e';x.fillRect(e.x-e.r,e.y-e.r-8,w*(e.hp/e.maxHp),3)}})}
})();
