const mineBoard=document.getElementById('mineBoard'),mineCount=document.getElementById('mineCount'),mineTime=document.getElementById('mineTime'),mineStatus=document.getElementById('mineStatus'),mineReset=document.getElementById('mineReset');
const MODES={easy:[9,9,10],normal:[16,16,40],hard:[16,30,99]};let rows,cols,totalMines,cells,started,ended,flags,opened,timer,time,mode='easy';
function reset(){clearInterval(timer);[rows,cols,totalMines]=MODES[mode];cells=Array.from({length:rows*cols},(_,i)=>({i,mine:false,open:false,flag:false,n:0}));started=false;ended=false;flags=0;opened=0;time=0;mineTime.textContent='000';mineCount.textContent=totalMines;mineReset.textContent='🙂';mineStatus.textContent='첫 칸을 선택하면 시작합니다.';mineBoard.style.setProperty('--cols',cols);render();}
function neighbors(i){const y=Math.floor(i/cols),x=i%cols,out=[];for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++){const ny=y+dy,nx=x+dx;if((dx||dy)&&ny>=0&&ny<rows&&nx>=0&&nx<cols)out.push(ny*cols+nx);}return out;}
function placeMines(safe){const blocked=new Set([safe,...neighbors(safe)]),pool=cells.map(c=>c.i).filter(i=>!blocked.has(i));for(let m=0;m<totalMines;m++){const pick=Math.floor(Math.random()*pool.length);cells[pool.splice(pick,1)[0]].mine=true;}cells.forEach(c=>c.n=neighbors(c.i).filter(i=>cells[i].mine).length);started=true;timer=setInterval(()=>{time=Math.min(999,time+1);mineTime.textContent=String(time).padStart(3,'0');},1000);mineStatus.textContent='안전한 칸을 모두 찾으세요.';}
function openCell(i){if(ended||cells[i].flag||cells[i].open)return;if(!started)placeMines(i);const cell=cells[i];cell.open=true;opened++;if(cell.mine){finish(false);return;}if(!cell.n)neighbors(i).forEach(openCell);if(opened===rows*cols-totalMines)finish(true);render();}
function toggleFlag(i){if(ended||cells[i].open)return;cells[i].flag=!cells[i].flag;flags+=cells[i].flag?1:-1;mineCount.textContent=totalMines-flags;render();}
function finish(win){ended=true;clearInterval(timer);mineReset.textContent=win?'😎':'😵';mineStatus.textContent=win?`${time}초 만에 지뢰를 모두 찾았습니다!`:'지뢰를 밟았습니다. 다시 도전하세요.';if(win)cells.filter(c=>c.mine).forEach(c=>c.flag=true);else cells.filter(c=>c.mine).forEach(c=>c.open=true);render();}
function render(){mineBoard.innerHTML='';cells.forEach(c=>{const b=document.createElement('button');b.type='button';b.className='mine-cell'+(c.open?' open':'')+(c.mine&&c.open?' exploded':'');b.setAttribute('role','gridcell');b.setAttribute('aria-label',c.flag?'깃발 표시':c.open?(c.mine?'지뢰':c.n?`주변 지뢰 ${c.n}개`:'빈 칸'):'닫힌 칸');if(c.flag)b.textContent='🚩';else if(c.open&&c.mine)b.textContent='💣';else if(c.open&&c.n){b.textContent=c.n;b.dataset.number=c.n;}let hold;b.addEventListener('click',()=>openCell(c.i));b.addEventListener('contextmenu',e=>{e.preventDefault();toggleFlag(c.i);});b.addEventListener('pointerdown',e=>{if(e.pointerType!=='mouse')hold=setTimeout(()=>toggleFlag(c.i),550);});b.addEventListener('pointerup',()=>clearTimeout(hold));b.addEventListener('pointercancel',()=>clearTimeout(hold));mineBoard.appendChild(b);});}
mineReset.addEventListener('click',reset);document.querySelectorAll('.difficulty button').forEach(button=>button.addEventListener('click',()=>{mode=button.dataset.mode;document.querySelectorAll('.difficulty button').forEach(b=>b.classList.toggle('active',b===button));reset();}));reset();
