const rhythmCanvas=document.getElementById('rhythm'),rx=rhythmCanvas.getContext('2d'),rhythmOverlay=document.getElementById('rhythmOverlay'),rhythmTitle=document.getElementById('rhythmTitle'),rhythmText=document.getElementById('rhythmText'),rhythmStart=document.getElementById('rhythmStart'),rhythmScore=document.getElementById('rhythmScore'),rhythmLevel=document.getElementById('rhythmLevel'),rhythmCombo=document.getElementById('rhythmCombo'),rhythmHealth=document.getElementById('rhythmHealth');
const rhythmRanking=GameRanking.create({game:'rhythm'}),LANE_KEYS=['D','F','J','K'],LANE_COLORS=['#72ddff','#b982ff','#f0b95b','#67d79d'],JUDGE_Y=590;
let notes=[],particles=[],score=0,combo=0,maxCombo=0,health=100,level=1,hits=0,bpm=100,spawnTimer=0,beat=0,running=false,paused=false,last=0,judgement='',judgeLife=0,musicAudio=null;
function getAudio(){if(!musicAudio)musicAudio=new(window.AudioContext||window.webkitAudioContext)();musicAudio.resume();return musicAudio;}
function musicTone(frequency,accent=false,delay=0){const a=getAudio(),o=a.createOscillator(),g=a.createGain(),now=a.currentTime+delay;o.type=accent?'square':'triangle';o.frequency.setValueAtTime(frequency,now);g.gain.setValueAtTime(accent?.045:.025,now);g.gain.exponentialRampToValueAtTime(.001,now+.13);o.connect(g).connect(a.destination);o.start(now);o.stop(now+.14);}
function resetRhythm(){notes=[];particles=[];score=0;combo=0;maxCombo=0;health=100;level=1;hits=0;bpm=100;spawnTimer=.4;beat=0;judgement='';judgeLife=0;updateRhythmHud();drawRhythm();}
function updateRhythmHud(){rhythmScore.textContent=`점수 ${score.toLocaleString('ko-KR')}`;rhythmLevel.textContent=`레벨 ${level} · ${bpm} BPM`;rhythmCombo.textContent=`콤보 ${combo}`;rhythmHealth.style.transform=`scaleX(${Math.max(0,health)/100})`;}
function noteSpeed(){return 225+(level-1)*18;}
function spawnBeat(){const lane=Math.floor(Math.random()*4);notes.push({lane,y:-24,hit:false});if(level>=3&&Math.random()<Math.min(.38,level*.045)){let other;do other=Math.floor(Math.random()*4);while(other===lane);notes.push({lane:other,y:-24,hit:false});}const scale=[261.63,293.66,329.63,392,440,523.25];musicTone(scale[beat%scale.length],beat%4===0,(JUDGE_Y+24)/noteSpeed());beat++;}
function burst(lane,color){const x=180+lane*120;for(let i=0;i<12;i++)particles.push({x,y:JUDGE_Y,vx:(Math.random()-.5)*180,vy:-40-Math.random()*110,a:1,color});}
function judge(lane){if(!running||paused)return;const candidates=notes.filter(n=>n.lane===lane&&!n.hit).sort((a,b)=>Math.abs(a.y-JUDGE_Y)-Math.abs(b.y-JUDGE_Y)),note=candidates[0];document.querySelector(`[data-lane="${lane}"]`)?.classList.add('active');setTimeout(()=>document.querySelector(`[data-lane="${lane}"]`)?.classList.remove('active'),80);if(!note||Math.abs(note.y-JUDGE_Y)>62){combo=0;health=Math.max(0,health-3);judgement='MISS';judgeLife=.35;GameAudio.play('fail');updateRhythmHud();return;}const distance=Math.abs(note.y-JUDGE_Y),perfect=distance<=25;note.hit=true;combo++;maxCombo=Math.max(maxCombo,combo);hits++;score+=(perfect?1000:500)+Math.min(500,combo*10);health=Math.min(100,health+(perfect?1.2:.5));judgement=perfect?'PERFECT':'GOOD';judgeLife=.5;burst(lane,LANE_COLORS[lane]);GameAudio.play(perfect?'clear':'step');const newLevel=Math.floor(hits/25)+1;if(newLevel>level){level=newLevel;bpm=Math.min(190,100+(level-1)*8);GameAudio.play('level');}updateRhythmHud();}
function missNote(note){note.hit=true;combo=0;health=Math.max(0,health-10);judgement='MISS';judgeLife=.45;GameAudio.play('fail');updateRhythmHud();}
function endRhythm(){if(!running)return;running=false;musicAudio?.suspend();GameAudio.play('fail');rhythmTitle.textContent='연주 종료';rhythmText.textContent=`${score.toLocaleString('ko-KR')}점 · 레벨 ${level} · 최대 콤보 ${maxCombo}`;rhythmStart.textContent='다시 연주';rhythmOverlay.hidden=false;rhythmRanking.finish(score,level);}
function updateRhythm(dt){const speed=noteSpeed();spawnTimer-=dt;if(spawnTimer<=0){spawnBeat();spawnTimer+=60/bpm;}notes.forEach(n=>{if(!n.hit)n.y+=speed*dt;});notes.forEach(n=>{if(!n.hit&&n.y>JUDGE_Y+70)missNote(n);});notes=notes.filter(n=>!n.hit);particles.forEach(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=260*dt;p.a-=dt*2.2;});particles=particles.filter(p=>p.a>0);judgeLife-=dt;if(health<=0)endRhythm();}
function drawRhythm(){const w=rhythmCanvas.width,h=rhythmCanvas.height,top=78,laneW=120,startX=120;const bg=rx.createLinearGradient(0,0,0,h);bg.addColorStop(0,'#17103a');bg.addColorStop(1,'#070713');rx.fillStyle=bg;rx.fillRect(0,0,w,h);for(let lane=0;lane<4;lane++){const x=startX+lane*laneW;rx.fillStyle=lane%2?'rgba(185,130,255,.07)':'rgba(114,221,255,.05)';rx.fillRect(x,top,laneW,h-top);rx.strokeStyle='rgba(210,195,255,.2)';rx.strokeRect(x,top,laneW,h-top);rx.fillStyle='rgba(10,8,28,.9)';rx.fillRect(x+4,JUDGE_Y-8,laneW-8,38);rx.strokeStyle=LANE_COLORS[lane];rx.lineWidth=3;rx.strokeRect(x+4,JUDGE_Y-8,laneW-8,38);rx.fillStyle='#f4f1ff';rx.font='900 18px system-ui';rx.textAlign='center';rx.fillText(LANE_KEYS[lane],x+laneW/2,JUDGE_Y+18);}notes.forEach(n=>{if(n.hit)return;const x=startX+n.lane*laneW+10;rx.shadowColor=LANE_COLORS[n.lane];rx.shadowBlur=15;rx.fillStyle=LANE_COLORS[n.lane];rx.beginPath();rx.roundRect(x,n.y-12,laneW-20,24,8);rx.fill();rx.shadowBlur=0;});particles.forEach(p=>{rx.globalAlpha=Math.max(0,p.a);rx.fillStyle=p.color;rx.fillRect(p.x,p.y,5,5);});rx.globalAlpha=1;if(judgeLife>0){rx.fillStyle=judgement==='PERFECT'?'#ffe498':judgement==='GOOD'?'#72ddff':'#ff6d82';rx.font='900 32px system-ui';rx.textAlign='center';rx.fillText(judgement,w/2,330);if(combo>1){rx.font='900 18px system-ui';rx.fillText(`${combo} COMBO`,w/2,358);}}}
function rhythmLoop(t){if(!running)return;const dt=Math.min((t-last)/1000,.04);last=t;if(!paused)updateRhythm(dt);drawRhythm();requestAnimationFrame(rhythmLoop);}
function startRhythm(){getAudio();GameAudio.play('click');rhythmRanking.reset();resetRhythm();running=true;paused=false;last=performance.now();rhythmOverlay.hidden=true;requestAnimationFrame(rhythmLoop);}
rhythmStart.addEventListener('click',()=>paused?(paused=false,getAudio(),rhythmOverlay.hidden=true,last=performance.now()):startRhythm());document.addEventListener('keydown',e=>{const map={KeyD:0,KeyF:1,KeyJ:2,KeyK:3};if(map[e.code]!==undefined){e.preventDefault();judge(map[e.code]);}if(e.code==='KeyP'&&running){paused=!paused;if(paused)musicAudio?.suspend();else getAudio();rhythmTitle.textContent='일시정지';rhythmText.textContent='계속하려면 P 키나 버튼을 누르세요.';rhythmStart.textContent='계속';rhythmOverlay.hidden=!paused;}});document.querySelectorAll('[data-lane]').forEach(button=>button.addEventListener('pointerdown',()=>judge(Number(button.dataset.lane))));resetRhythm();
