const shootCanvas=document.getElementById('shooter'),sx=shootCanvas.getContext('2d'),shootOverlay=document.getElementById('shootOverlay'),shootTitle=document.getElementById('shootTitle'),shootText=document.getElementById('shootText'),shootStart=document.getElementById('shootStart'),shootScore=document.getElementById('shootScore'),shootWave=document.getElementById('shootWave'),shootLives=document.getElementById('shootLives');
let ship,shots,enemies,enemyShots,stars,score,wave,lives,running=false,paused=false,last=0,enemyDir=1,enemyFire=0,fireDelay=0,keys={};
function resetShooter(){ship={x:450,y:545,w:34,h:28,speed:330,invincible:0};shots=[];enemyShots=[];score=0;wave=1;lives=3;stars=Array.from({length:90},()=>({x:Math.random()*900,y:Math.random()*600,s:1+Math.random()*2}));spawnWave();updateShootHud();}
function spawnWave(){enemies=[];const rows=Math.min(5,3+Math.floor(wave/2)),cols=9;for(let r=0;r<rows;r++)for(let c=0;c<cols;c++)enemies.push({x:145+c*76,y:75+r*54,w:30,h:24,row:r,phase:Math.random()*6.28});enemyDir=1;}
function updateShootHud(){shootScore.textContent=`점수 ${score.toLocaleString('ko-KR')}`;shootWave.textContent=`웨이브 ${wave}`;shootLives.textContent=`생명 ${'♥'.repeat(Math.max(0,lives))}`;}
function hit(a,b){return a.x-a.w/2<b.x+b.w/2&&a.x+a.w/2>b.x-b.w/2&&a.y-a.h/2<b.y+b.h/2&&a.y+a.h/2>b.y-b.h/2;}
function fire(){if(fireDelay<=0&&running&&!paused){shots.push({x:ship.x,y:ship.y-22,w:4,h:14});fireDelay=.18;}}
function finishShooter(){running=false;shootTitle.textContent='게임 오버';shootText.textContent=`${score.toLocaleString('ko-KR')}점 · 웨이브 ${wave}까지 도달했습니다.`;shootStart.textContent='다시 시작';shootOverlay.hidden=false;}
function updateShooter(dt){stars.forEach(s=>{s.y+=s.s*30*dt;if(s.y>600){s.y=0;s.x=Math.random()*900;}});let dx=(keys.ArrowRight||keys.KeyD?1:0)-(keys.ArrowLeft||keys.KeyA?1:0);ship.x=Math.max(24,Math.min(876,ship.x+dx*ship.speed*dt));if(keys.Space)fire();fireDelay-=dt;ship.invincible-=dt;shots.forEach(b=>b.y-=520*dt);shots=shots.filter(b=>b.y>-20);enemyShots.forEach(b=>b.y+=(190+wave*14)*dt);enemyShots=enemyShots.filter(b=>b.y<630);let edge=false;enemies.forEach(e=>{e.x+=enemyDir*(30+wave*5)*dt;if(e.x<25||e.x>875)edge=true;});if(edge){enemyDir*=-1;enemies.forEach(e=>e.y+=12);}enemyFire-=dt;if(enemyFire<=0&&enemies.length){const e=enemies[Math.floor(Math.random()*enemies.length)];enemyShots.push({x:e.x,y:e.y+16,w:5,h:13});enemyFire=Math.max(.25,1.05-wave*.06)*(.65+Math.random());}for(let i=enemies.length-1;i>=0;i--)for(let j=shots.length-1;j>=0;j--)if(hit(enemies[i],shots[j])){score+=100+enemies[i].row*20;enemies.splice(i,1);shots.splice(j,1);updateShootHud();break;}if(ship.invincible<=0)for(let i=enemyShots.length-1;i>=0;i--)if(hit(ship,enemyShots[i])){enemyShots.splice(i,1);lives--;ship.invincible=2;updateShootHud();if(lives<=0)finishShooter();break;}if(enemies.some(e=>e.y>510))finishShooter();if(running&&!enemies.length){wave++;spawnWave();updateShootHud();}}
function drawShip(){if(ship.invincible>0&&Math.floor(ship.invincible*8)%2)return;sx.fillStyle='#72ddff';sx.beginPath();sx.moveTo(ship.x,ship.y-18);sx.lineTo(ship.x-18,ship.y+14);sx.lineTo(ship.x,ship.y+7);sx.lineTo(ship.x+18,ship.y+14);sx.closePath();sx.fill();sx.fillStyle='#f0b95b';sx.fillRect(ship.x-4,ship.y+8,8,13);}
function drawEnemy(e,t){sx.save();sx.translate(e.x,e.y+Math.sin(t*.004+e.phase)*4);sx.fillStyle=['#ed6a5a','#a96df0','#67d79d','#f0b95b','#72ddff'][e.row%5];sx.fillRect(-12,-10,24,18);sx.fillRect(-18,-4,36,10);sx.fillStyle='#071018';sx.fillRect(-6,-4,4,4);sx.fillRect(2,-4,4,4);sx.restore();}
function drawShooter(t=0){sx.fillStyle='#050913';sx.fillRect(0,0,900,600);sx.fillStyle='#dcecff';stars.forEach(s=>sx.fillRect(s.x,s.y,s.s,s.s));shots.forEach(b=>{sx.fillStyle='#ffe69b';sx.fillRect(b.x-2,b.y-7,4,14);});enemyShots.forEach(b=>{sx.fillStyle='#ff6378';sx.fillRect(b.x-3,b.y-7,6,14);});enemies.forEach(e=>drawEnemy(e,t));drawShip();}
function shootLoop(t){if(!running)return;const dt=Math.min((t-last)/1000,.033);last=t;if(!paused)updateShooter(dt);drawShooter(t);requestAnimationFrame(shootLoop);}
function startShooter(){resetShooter();running=true;paused=false;last=performance.now();shootOverlay.hidden=true;requestAnimationFrame(shootLoop);}
shootStart.addEventListener('click',()=>{if(paused){paused=false;shootOverlay.hidden=true;last=performance.now();}else startShooter();});document.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','Space'].includes(e.code))e.preventDefault();keys[e.code]=true;if(e.code==='KeyP'&&running){paused=!paused;shootText.textContent='계속하려면 P 키를 누르세요.';shootTitle.textContent='일시정지';shootStart.textContent='계속';shootOverlay.hidden=!paused;}if(e.code==='Space')fire();});document.addEventListener('keyup',e=>keys[e.code]=false);document.querySelectorAll('[data-move]').forEach(b=>{const code=b.dataset.move==='left'?'ArrowLeft':'ArrowRight';b.addEventListener('pointerdown',()=>keys[code]=true);b.addEventListener('pointerup',()=>keys[code]=false);b.addEventListener('pointercancel',()=>keys[code]=false);});document.getElementById('touchFire').addEventListener('pointerdown',fire);resetShooter();drawShooter();
