const shootCanvas=document.getElementById('shooter'),sx=shootCanvas.getContext('2d');
const shootOverlay=document.getElementById('shootOverlay'),shootTitle=document.getElementById('shootTitle'),shootText=document.getElementById('shootText'),shootStart=document.getElementById('shootStart');
const shootScore=document.getElementById('shootScore'),shootWave=document.getElementById('shootWave'),shootLives=document.getElementById('shootLives'),shootPower=document.getElementById('shootPower');
const upgradeOverlay=document.getElementById('shootUpgrade'),upgradeTitle=document.getElementById('upgradeTitle'),upgradeText=document.getElementById('upgradeText'),upgradeChoices=document.getElementById('shootChoices');
const shooterRanking=GameRanking.create({game:'shooter'}),POWER_TYPES=['heal','drones','laser'];
let ship,shots,enemies,enemyShots,powerups,stars,score,wave,lives,running=false,paused=false,choosing=false,last=0,enemyDir=1,enemyFire=0,fireDelay=0,keys={},enemyId=0,specialKind=null;

const midSkills=[
  {name:'강화 탄환',desc:'공격력 +1',apply:()=>ship.damage+=1},
  {name:'고속 장전',desc:'공격 속도 15% 증가',apply:()=>ship.fireRate*=.85},
  {name:'기체 보강',desc:'최대 생명 +1, 생명 1 회복',apply:()=>{ship.maxLives++;lives=Math.min(ship.maxLives,lives+1)}},
  {name:'고출력 엔진',desc:'이동 속도 12% 증가',apply:()=>ship.speed*=1.12},
  {name:'집중 사격',desc:'보조기체 획득, 이미 있으면 공격력 +1',apply:()=>ship.drones?ship.damage++:ship.drones=true}
];
const bossSkills=[
  {name:'초월 화력',desc:'공격력 +3',apply:()=>ship.damage+=3},
  {name:'광속 장전',desc:'공격 속도 30% 증가',apply:()=>ship.fireRate*=.7},
  {name:'완전 재생',desc:'최대 생명 +2, 생명 완전 회복',apply:()=>{ship.maxLives+=2;lives=ship.maxLives}},
  {name:'트윈 가디언',desc:'보조기체 획득, 보조기체 탄환 공격력 2배',apply:()=>{ship.drones=true;ship.dronePower=2}},
  {name:'플라즈마 레이저',desc:'관통 레이저 획득, 레이저 공격력 +2',apply:()=>{ship.laser=true;ship.damage+=2}}
];

function resetShooter(){ship={x:450,y:545,w:34,h:28,speed:330,invincible:0,drones:false,laser:false,damage:1,fireRate:1,maxLives:3,dronePower:1};shots=[];enemyShots=[];powerups=[];score=0;wave=1;lives=3;choosing=false;stars=Array.from({length:90},()=>({x:Math.random()*900,y:Math.random()*600,s:1+Math.random()*2}));spawnWave();updateShootHud();}
function makeEnemy(type,x,y,row=0){const levelScale=1+Math.floor((wave-1)/3)*.35;const stats={normal:{w:30,h:24,hp:1,color:'#ed6a5a',score:100},rapid:{w:32,h:24,hp:2,color:'#f0b95b',score:180},tank:{w:42,h:32,hp:Math.ceil(5*levelScale),color:'#67d79d',score:280},midboss:{w:92,h:62,hp:35+wave*4,color:'#a96df0',score:3000},boss:{w:138,h:88,hp:100+wave*8,color:'#ff5573',score:10000}}[type];return{id:++enemyId,type,x,y,row,phase:Math.random()*6.28,maxHp:stats.hp,hp:stats.hp,...stats};}
function spawnWave(){enemies=[];specialKind=wave%10===0?'boss':wave%5===0?'midboss':null;if(specialKind){enemies.push(makeEnemy(specialKind,450,specialKind==='boss'?125:105));}else{const rows=Math.min(5,3+Math.floor(wave/3)),cols=9;for(let r=0;r<rows;r++)for(let c=0;c<cols;c++){const roll=Math.random(),type=wave>=3&&roll<.16?'tank':wave>=2&&roll<.36?'rapid':'normal';enemies.push(makeEnemy(type,145+c*76,75+r*54,r));}}enemyDir=1;enemyFire=.8;}
function updateShootHud(){shootScore.textContent=`점수 ${score.toLocaleString('ko-KR')}`;shootWave.textContent=`레벨 ${wave}`;shootLives.textContent=`생명 ${'♥'.repeat(Math.max(0,lives))}/${ship?.maxLives||3}`;const powers=[];if(ship?.drones)powers.push('보조기체');if(ship?.laser)powers.push('레이저');shootPower.textContent=powers.length?powers.join(' + '):`공격력 ${ship?.damage||1}`;}
function hit(a,b){return a.x-a.w/2<b.x+b.w/2&&a.x+a.w/2>b.x-b.w/2&&a.y-a.h/2<b.y+b.h/2&&a.y+a.h/2>b.y-b.h/2;}
function addShot(x,y,drone=false){shots.push({x,y,w:ship.laser?7:4,h:ship.laser?34:14,laser:ship.laser,damage:ship.damage*(drone?ship.dronePower:1),hits:new Set()});}
function fire(){if(fireDelay<=0&&running&&!paused&&!choosing){addShot(ship.x,ship.y-22);if(ship.drones){addShot(ship.x-31,ship.y-12,true);addShot(ship.x+31,ship.y-12,true);}fireDelay=(ship.laser?.12:.18)*ship.fireRate;}}
function dropPowerup(x,y){if(Math.random()>.14)return;const type=POWER_TYPES[Math.floor(Math.random()*POWER_TYPES.length)],angle=Math.random()*Math.PI*2,speed=90+Math.random()*55;powerups.push({x,y,w:28,h:28,type,vx:Math.cos(angle)*speed,vy:Math.sin(angle)*speed||90,spin:0});}
function collectPowerup(item){if(item.type==='heal')lives=Math.min(ship.maxLives,lives+1);if(item.type==='drones')ship.drones=true;if(item.type==='laser')ship.laser=true;score+=250;updateShootHud();}
function finishShooter(){if(!running)return;running=false;shootTitle.textContent='게임 오버';shootText.textContent=`${score.toLocaleString('ko-KR')}점 · 레벨 ${wave}까지 도달했습니다.`;shootStart.textContent='다시 시작';shootOverlay.hidden=false;shooterRanking.finish(score,wave);}

function fireEnemy(e){const speed=190+wave*12;if(e.type==='boss'){for(const vx of [-150,-75,0,75,150])enemyShots.push({x:e.x,y:e.y+45,vx,vy:speed,w:7,h:16});}else if(e.type==='midboss'){for(const vx of [-90,0,90])enemyShots.push({x:e.x,y:e.y+32,vx,vy:speed,w:7,h:15});}else if(e.type==='rapid'){enemyShots.push({x:e.x-7,y:e.y+14,vx:-25,vy:speed+65,w:5,h:13},{x:e.x+7,y:e.y+14,vx:25,vy:speed+65,w:5,h:13});}else if(e.type==='tank')enemyShots.push({x:e.x,y:e.y+18,vx:0,vy:speed*.7,w:10,h:20});else enemyShots.push({x:e.x,y:e.y+14,vx:0,vy:speed,w:5,h:13});}
function chooseFiringEnemy(){const weighted=[];enemies.forEach(e=>{const weight=e.type==='rapid'?5:e.type==='boss'||e.type==='midboss'?8:1;for(let i=0;i<weight;i++)weighted.push(e);});return weighted[Math.floor(Math.random()*weighted.length)];}
function updatePowerups(dt){for(let i=powerups.length-1;i>=0;i--){const p=powerups[i];p.x+=p.vx*dt;p.y+=p.vy*dt;p.spin+=dt*3;if(p.x<18){p.x=18;p.vx=Math.abs(p.vx);}if(p.x>882){p.x=882;p.vx=-Math.abs(p.vx);}if(p.y<48){p.y=48;p.vy=Math.abs(p.vy);}if(p.y>582){p.y=582;p.vy=-Math.abs(p.vy);}if(hit(ship,p)){collectPowerup(p);powerups.splice(i,1);}}}
function defeatEnemy(index){const e=enemies[index];score+=e.score+e.row*20;if(e.type==='normal'||e.type==='rapid'||e.type==='tank')dropPowerup(e.x,e.y);enemies.splice(index,1);updateShootHud();}
function openUpgrade(kind){choosing=true;const strong=kind==='boss',pool=[...(strong?bossSkills:midSkills)].sort(()=>Math.random()-.5).slice(0,3);upgradeTitle.textContent=strong?'보스 격파: 강력한 스킬 선택':'중간보스 격파: 스킬 선택';upgradeText.textContent=strong?'보스의 에너지를 흡수했습니다. 강화 효과가 큰 스킬 하나를 선택하세요.':'다음 전투에 사용할 스킬 하나를 선택하세요.';upgradeChoices.replaceChildren();pool.forEach(skill=>{const button=document.createElement('button');button.type='button';button.className='shoot-skill';button.innerHTML=`<strong>${skill.name}</strong><span>${skill.desc}</span>`;button.addEventListener('click',()=>{skill.apply();choosing=false;upgradeOverlay.hidden=true;wave++;spawnWave();updateShootHud();last=performance.now();});upgradeChoices.appendChild(button);});upgradeOverlay.hidden=false;}

function updateShooter(dt){stars.forEach(s=>{s.y+=s.s*30*dt;if(s.y>600){s.y=0;s.x=Math.random()*900;}});let dx=(keys.ArrowRight||keys.KeyD?1:0)-(keys.ArrowLeft||keys.KeyA?1:0);ship.x=Math.max(ship.drones?55:24,Math.min(ship.drones?845:876,ship.x+dx*ship.speed*dt));if(keys.Space)fire();fireDelay-=dt;ship.invincible-=dt;shots.forEach(b=>b.y-=(b.laser?690:520)*dt);shots=shots.filter(b=>b.y>-40);enemyShots.forEach(b=>{b.x+=(b.vx||0)*dt;b.y+=b.vy*dt;});enemyShots=enemyShots.filter(b=>b.y<630&&b.x>-30&&b.x<930);updatePowerups(dt);
  let edge=false;const moveSpeed=specialKind?(specialKind==='boss'?55:70):(30+wave*5);enemies.forEach(e=>{e.x+=enemyDir*moveSpeed*dt;if(e.x-e.w/2<18||e.x+e.w/2>882)edge=true;});if(edge){enemyDir*=-1;enemies.forEach(e=>e.y+=specialKind?5:12);}enemyFire-=dt;if(enemyFire<=0&&enemies.length){const e=chooseFiringEnemy();fireEnemy(e);enemyFire=e.type==='rapid'?.32:e.type==='boss'?.5:e.type==='midboss'?.65:Math.max(.28,.95-wave*.045)*(.7+Math.random()*.5);}
  for(let i=enemies.length-1;i>=0;i--)for(let j=shots.length-1;j>=0;j--){const b=shots[j],e=enemies[i];if(hit(e,b)&&!b.hits.has(e.id)){b.hits.add(e.id);e.hp-=b.damage;if(!b.laser)shots.splice(j,1);if(e.hp<=0)defeatEnemy(i);break;}}
  if(ship.invincible<=0)for(let i=enemyShots.length-1;i>=0;i--)if(hit(ship,enemyShots[i])){enemyShots.splice(i,1);lives--;ship.invincible=2;updateShootHud();if(lives<=0)finishShooter();break;}if(enemies.some(e=>e.y+e.h/2>510))finishShooter();if(running&&!enemies.length&&!choosing){if(specialKind)openUpgrade(specialKind);else{wave++;spawnWave();updateShootHud();}}}

function drawMiniShip(x,y){sx.fillStyle='#8ff0ff';sx.beginPath();sx.moveTo(x,y-10);sx.lineTo(x-10,y+8);sx.lineTo(x,y+4);sx.lineTo(x+10,y+8);sx.closePath();sx.fill();sx.fillStyle='#f0b95b';sx.fillRect(x-2,y+5,4,7);}
function drawShip(){if(ship.invincible>0&&Math.floor(ship.invincible*8)%2)return;if(ship.drones){drawMiniShip(ship.x-31,ship.y+2);drawMiniShip(ship.x+31,ship.y+2);}sx.fillStyle=ship.laser?'#b982ff':'#72ddff';sx.beginPath();sx.moveTo(ship.x,ship.y-18);sx.lineTo(ship.x-18,ship.y+14);sx.lineTo(ship.x,ship.y+7);sx.lineTo(ship.x+18,ship.y+14);sx.closePath();sx.fill();sx.fillStyle='#f0b95b';sx.fillRect(ship.x-4,ship.y+8,8,13);}
function drawEnemy(e,t){sx.save();sx.translate(e.x,e.y+Math.sin(t*.004+e.phase)*(e.type==='boss'?2:4));sx.fillStyle=e.color;if(e.type==='boss'){sx.fillRect(-60,-34,120,60);sx.fillRect(-78,-12,156,25);sx.fillStyle='#ffd0d8';sx.fillRect(-25,-18,50,20);}else if(e.type==='midboss'){sx.fillRect(-38,-24,76,45);sx.fillRect(-50,-7,100,18);sx.fillStyle='#e8d7ff';sx.fillRect(-15,-12,30,14);}else if(e.type==='tank'){sx.fillRect(-21,-15,42,30);sx.fillStyle='#baf5d2';sx.fillRect(-12,-7,24,11);}else{sx.fillRect(-12,-10,24,18);sx.fillRect(-18,-4,36,10);sx.fillStyle='#071018';sx.fillRect(-6,-4,4,4);sx.fillRect(2,-4,4,4);}sx.restore();if(e.maxHp>1){const width=e.type==='boss'?160:e.type==='midboss'?110:e.w;sx.fillStyle='#35191b';sx.fillRect(e.x-width/2,e.y-e.h/2-13,width,6);sx.fillStyle=e.type==='boss'?'#ff5573':'#67d79d';sx.fillRect(e.x-width/2,e.y-e.h/2-13,width*Math.max(0,e.hp/e.maxHp),6);}}
function drawPowerup(p){const colors={heal:'#67d79d',drones:'#72ddff',laser:'#b982ff'},labels={heal:'+',drones:'D',laser:'L'};sx.save();sx.translate(p.x,p.y);sx.rotate(p.spin);sx.shadowColor=colors[p.type];sx.shadowBlur=16;sx.fillStyle=colors[p.type];sx.fillRect(-13,-13,26,26);sx.shadowBlur=0;sx.strokeStyle='#fff';sx.lineWidth=2;sx.strokeRect(-11,-11,22,22);sx.rotate(-p.spin);sx.fillStyle='#071018';sx.font='900 17px system-ui';sx.textAlign='center';sx.textBaseline='middle';sx.fillText(labels[p.type],0,1);sx.restore();}
function drawShooter(t=0){sx.fillStyle='#050913';sx.fillRect(0,0,900,600);sx.fillStyle='#dcecff';stars.forEach(s=>sx.fillRect(s.x,s.y,s.s,s.s));shots.forEach(b=>{sx.fillStyle=b.laser?'#c89cff':'#ffe69b';if(b.laser){sx.shadowColor='#b982ff';sx.shadowBlur=14;}sx.fillRect(b.x-b.w/2,b.y-b.h/2,b.w,b.h);sx.shadowBlur=0;});enemyShots.forEach(b=>{sx.fillStyle='#ff6378';sx.fillRect(b.x-b.w/2,b.y-b.h/2,b.w,b.h);});enemies.forEach(e=>drawEnemy(e,t));powerups.forEach(drawPowerup);drawShip();}
function shootLoop(t){if(!running)return;const dt=Math.min((t-last)/1000,.033);last=t;if(!paused&&!choosing)updateShooter(dt);drawShooter(t);requestAnimationFrame(shootLoop);}
function startShooter(){shooterRanking.reset();resetShooter();running=true;paused=false;last=performance.now();shootOverlay.hidden=true;upgradeOverlay.hidden=true;requestAnimationFrame(shootLoop);}

shootStart.addEventListener('click',()=>{if(paused){paused=false;shootOverlay.hidden=true;last=performance.now();}else startShooter();});document.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','Space'].includes(e.code))e.preventDefault();keys[e.code]=true;if(e.code==='KeyP'&&running&&!choosing){paused=!paused;shootText.textContent='계속하려면 P 키를 누르세요.';shootTitle.textContent='일시정지';shootStart.textContent='계속';shootOverlay.hidden=!paused;}if(e.code==='Space')fire();});document.addEventListener('keyup',e=>keys[e.code]=false);document.querySelectorAll('[data-move]').forEach(b=>{const code=b.dataset.move==='left'?'ArrowLeft':'ArrowRight';b.addEventListener('pointerdown',()=>keys[code]=true);b.addEventListener('pointerup',()=>keys[code]=false);b.addEventListener('pointercancel',()=>keys[code]=false);});document.getElementById('touchFire').addEventListener('pointerdown',fire);resetShooter();drawShooter();
