const shootCanvas=document.getElementById('shooter'),sx=shootCanvas.getContext('2d'),shootOverlay=document.getElementById('shootOverlay'),shootTitle=document.getElementById('shootTitle'),shootText=document.getElementById('shootText'),shootStart=document.getElementById('shootStart'),shootScore=document.getElementById('shootScore'),shootWave=document.getElementById('shootWave'),shootLives=document.getElementById('shootLives'),shootPower=document.getElementById('shootPower');
const shooterRanking=GameRanking.create({game:'shooter'}),POWER_TYPES=['heal','drones','laser'];
let ship,shots,enemies,enemyShots,powerups,stars,score,wave,lives,running=false,paused=false,last=0,enemyDir=1,enemyFire=0,fireDelay=0,keys={};

function resetShooter(){ship={x:450,y:545,w:34,h:28,speed:330,invincible:0,drones:false,laser:false};shots=[];enemyShots=[];powerups=[];score=0;wave=1;lives=3;stars=Array.from({length:90},()=>({x:Math.random()*900,y:Math.random()*600,s:1+Math.random()*2}));spawnWave();updateShootHud();}
function spawnWave(){enemies=[];const rows=Math.min(5,3+Math.floor(wave/2)),cols=9;for(let r=0;r<rows;r++)for(let c=0;c<cols;c++)enemies.push({x:145+c*76,y:75+r*54,w:30,h:24,row:r,phase:Math.random()*6.28});enemyDir=1;}
function updateShootHud(){shootScore.textContent=`점수 ${score.toLocaleString('ko-KR')}`;shootWave.textContent=`레벨 ${wave}`;shootLives.textContent=`생명 ${'♥'.repeat(Math.max(0,lives))}`;const powers=[];if(ship?.drones)powers.push('보조기체');if(ship?.laser)powers.push('레이저');shootPower.textContent=powers.length?powers.join(' + '):'기본 무기';}
function hit(a,b){return a.x-a.w/2<b.x+b.w/2&&a.x+a.w/2>b.x-b.w/2&&a.y-a.h/2<b.y+b.h/2&&a.y+a.h/2>b.y-b.h/2;}
function addShot(x,y){shots.push({x,y,w:ship.laser?7:4,h:ship.laser?34:14,laser:ship.laser});}
function fire(){if(fireDelay<=0&&running&&!paused){addShot(ship.x,ship.y-22);if(ship.drones){addShot(ship.x-31,ship.y-12);addShot(ship.x+31,ship.y-12);}fireDelay=ship.laser?.12:.18;}}
function dropPowerup(x,y){if(Math.random()>.14)return;const type=POWER_TYPES[Math.floor(Math.random()*POWER_TYPES.length)],angle=Math.random()*Math.PI*2,speed=90+Math.random()*55;powerups.push({x,y,w:28,h:28,type,vx:Math.cos(angle)*speed,vy:Math.sin(angle)*speed||90,spin:0});}
function collectPowerup(item){if(item.type==='heal')lives=Math.min(5,lives+1);if(item.type==='drones')ship.drones=true;if(item.type==='laser')ship.laser=true;score+=250;updateShootHud();}
function finishShooter(){if(!running)return;running=false;shootTitle.textContent='게임 오버';shootText.textContent=`${score.toLocaleString('ko-KR')}점 · 레벨 ${wave}까지 도달했습니다.`;shootStart.textContent='다시 시작';shootOverlay.hidden=false;shooterRanking.finish(score,wave);}

function updatePowerups(dt){for(let i=powerups.length-1;i>=0;i--){const p=powerups[i];p.x+=p.vx*dt;p.y+=p.vy*dt;p.spin+=dt*3;if(p.x<18){p.x=18;p.vx=Math.abs(p.vx);}if(p.x>882){p.x=882;p.vx=-Math.abs(p.vx);}if(p.y<48){p.y=48;p.vy=Math.abs(p.vy);}if(p.y>582){p.y=582;p.vy=-Math.abs(p.vy);}if(hit(ship,p)){collectPowerup(p);powerups.splice(i,1);}}}
function updateShooter(dt){stars.forEach(s=>{s.y+=s.s*30*dt;if(s.y>600){s.y=0;s.x=Math.random()*900;}});let dx=(keys.ArrowRight||keys.KeyD?1:0)-(keys.ArrowLeft||keys.KeyA?1:0);ship.x=Math.max(ship.drones?55:24,Math.min(ship.drones?845:876,ship.x+dx*ship.speed*dt));if(keys.Space)fire();fireDelay-=dt;ship.invincible-=dt;shots.forEach(b=>b.y-=(b.laser?690:520)*dt);shots=shots.filter(b=>b.y>-40);enemyShots.forEach(b=>b.y+=(190+wave*14)*dt);enemyShots=enemyShots.filter(b=>b.y<630);updatePowerups(dt);
  let edge=false;enemies.forEach(e=>{e.x+=enemyDir*(30+wave*5)*dt;if(e.x<25||e.x>875)edge=true;});if(edge){enemyDir*=-1;enemies.forEach(e=>e.y+=12);}enemyFire-=dt;if(enemyFire<=0&&enemies.length){const e=enemies[Math.floor(Math.random()*enemies.length)];enemyShots.push({x:e.x,y:e.y+16,w:5,h:13});enemyFire=Math.max(.25,1.05-wave*.06)*(.65+Math.random());}
  for(let i=enemies.length-1;i>=0;i--)for(let j=shots.length-1;j>=0;j--)if(hit(enemies[i],shots[j])){const defeated=enemies[i];score+=100+defeated.row*20;dropPowerup(defeated.x,defeated.y);enemies.splice(i,1);if(!shots[j].laser)shots.splice(j,1);updateShootHud();break;}
  if(ship.invincible<=0)for(let i=enemyShots.length-1;i>=0;i--)if(hit(ship,enemyShots[i])){enemyShots.splice(i,1);lives--;ship.invincible=2;updateShootHud();if(lives<=0)finishShooter();break;}if(enemies.some(e=>e.y>510))finishShooter();if(running&&!enemies.length){wave++;spawnWave();updateShootHud();}}

function drawMiniShip(x,y){sx.fillStyle='#8ff0ff';sx.beginPath();sx.moveTo(x,y-10);sx.lineTo(x-10,y+8);sx.lineTo(x,y+4);sx.lineTo(x+10,y+8);sx.closePath();sx.fill();sx.fillStyle='#f0b95b';sx.fillRect(x-2,y+5,4,7);}
function drawShip(){if(ship.invincible>0&&Math.floor(ship.invincible*8)%2)return;if(ship.drones){drawMiniShip(ship.x-31,ship.y+2);drawMiniShip(ship.x+31,ship.y+2);}sx.fillStyle=ship.laser?'#b982ff':'#72ddff';sx.beginPath();sx.moveTo(ship.x,ship.y-18);sx.lineTo(ship.x-18,ship.y+14);sx.lineTo(ship.x,ship.y+7);sx.lineTo(ship.x+18,ship.y+14);sx.closePath();sx.fill();sx.fillStyle='#f0b95b';sx.fillRect(ship.x-4,ship.y+8,8,13);}
function drawEnemy(e,t){sx.save();sx.translate(e.x,e.y+Math.sin(t*.004+e.phase)*4);sx.fillStyle=['#ed6a5a','#a96df0','#67d79d','#f0b95b','#72ddff'][e.row%5];sx.fillRect(-12,-10,24,18);sx.fillRect(-18,-4,36,10);sx.fillStyle='#071018';sx.fillRect(-6,-4,4,4);sx.fillRect(2,-4,4,4);sx.restore();}
function drawPowerup(p){const colors={heal:'#67d79d',drones:'#72ddff',laser:'#b982ff'},labels={heal:'+',drones:'D',laser:'L'};sx.save();sx.translate(p.x,p.y);sx.rotate(p.spin);sx.shadowColor=colors[p.type];sx.shadowBlur=16;sx.fillStyle=colors[p.type];sx.fillRect(-13,-13,26,26);sx.shadowBlur=0;sx.strokeStyle='#fff';sx.lineWidth=2;sx.strokeRect(-11,-11,22,22);sx.rotate(-p.spin);sx.fillStyle='#071018';sx.font='900 17px system-ui';sx.textAlign='center';sx.textBaseline='middle';sx.fillText(labels[p.type],0,1);sx.restore();}
function drawShooter(t=0){sx.fillStyle='#050913';sx.fillRect(0,0,900,600);sx.fillStyle='#dcecff';stars.forEach(s=>sx.fillRect(s.x,s.y,s.s,s.s));shots.forEach(b=>{sx.fillStyle=b.laser?'#c89cff':'#ffe69b';if(b.laser){sx.shadowColor='#b982ff';sx.shadowBlur=14;}sx.fillRect(b.x-b.w/2,b.y-b.h/2,b.w,b.h);sx.shadowBlur=0;});enemyShots.forEach(b=>{sx.fillStyle='#ff6378';sx.fillRect(b.x-3,b.y-7,6,14);});enemies.forEach(e=>drawEnemy(e,t));powerups.forEach(drawPowerup);drawShip();}
function shootLoop(t){if(!running)return;const dt=Math.min((t-last)/1000,.033);last=t;if(!paused)updateShooter(dt);drawShooter(t);requestAnimationFrame(shootLoop);}
function startShooter(){shooterRanking.reset();resetShooter();running=true;paused=false;last=performance.now();shootOverlay.hidden=true;requestAnimationFrame(shootLoop);}

shootStart.addEventListener('click',()=>{if(paused){paused=false;shootOverlay.hidden=true;last=performance.now();}else startShooter();});document.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','Space'].includes(e.code))e.preventDefault();keys[e.code]=true;if(e.code==='KeyP'&&running){paused=!paused;shootText.textContent='계속하려면 P 키를 누르세요.';shootTitle.textContent='일시정지';shootStart.textContent='계속';shootOverlay.hidden=!paused;}if(e.code==='Space')fire();});document.addEventListener('keyup',e=>keys[e.code]=false);document.querySelectorAll('[data-move]').forEach(b=>{const code=b.dataset.move==='left'?'ArrowLeft':'ArrowRight';b.addEventListener('pointerdown',()=>keys[code]=true);b.addEventListener('pointerup',()=>keys[code]=false);b.addEventListener('pointercancel',()=>keys[code]=false);});document.getElementById('touchFire').addEventListener('pointerdown',fire);resetShooter();drawShooter();
