const stairsCanvas=document.getElementById('stairs'),stx=stairsCanvas.getContext('2d'),stairsOverlay=document.getElementById('stairsOverlay'),stairsTitle=document.getElementById('stairsTitle'),stairsText=document.getElementById('stairsText'),stairsStart=document.getElementById('stairsStart'),stairsScore=document.getElementById('stairsScore'),stairsBest=document.getElementById('stairsBest'),stairsTime=document.getElementById('stairsTime');
const stairsLevel=document.getElementById('stairsLevel'),stairsRanking=GameRanking.create({game:'stairs'});
let stairPath=[],stepIndex=0,stairScore=0,timeLeft=1,runningStairs=false,lastStairTime=0,flash='',best=Number(localStorage.getItem('stairsBest')||0),particles=[];
function makePath(){stairPath=[0];for(let i=1;i<80;i++)stairPath.push(stairPath[i-1]+(Math.random()<.5?-1:1));}
function extendPath(){while(stairPath.length-stepIndex<50)stairPath.push(stairPath[stairPath.length-1]+(Math.random()<.5?-1:1));}
function resetStairs(){makePath();stepIndex=0;stairScore=0;timeLeft=1;particles=[];updateStairHud();drawStairs();}
function currentStairLevel(){return Math.floor(stairScore/10)+1;}
function updateStairHud(){stairsScore.textContent=`${stairScore} 계단`;stairsLevel.textContent=`레벨 ${currentStairLevel()}`;stairsBest.textContent=`최고 ${best}`;stairsTime.style.transform=`scaleX(${Math.max(0,timeLeft)})`;}
function expected(){return stairPath[stepIndex+1]>stairPath[stepIndex]?'right':'left';}
function step(direction){if(!runningStairs)return;if(direction!==expected()){endStairs('방향을 잘못 눌렀습니다.');return;}stepIndex++;stairScore++;timeLeft=Math.min(1,timeLeft+.12);flash=direction;for(let i=0;i<8;i++)particles.push({x:360+(stairPath[stepIndex]-stairPath[stepIndex-1])*58,y:515,vx:(Math.random()-.5)*100,vy:-30-Math.random()*80,a:1});if(stairScore>best){best=stairScore;localStorage.setItem('stairsBest',best);}extendPath();updateStairHud();}
function endStairs(message){runningStairs=false;stairsTitle.textContent='도전 종료';stairsText.textContent=`${message} 기록은 ${stairScore}계단 · 레벨 ${currentStairLevel()}입니다.`;stairsStart.textContent='다시 도전';stairsOverlay.hidden=false;updateStairHud();stairsRanking.finish(stairScore*100,currentStairLevel());}
function startStairs(){stairsRanking.reset();resetStairs();runningStairs=true;lastStairTime=performance.now();stairsOverlay.hidden=true;requestAnimationFrame(stairLoop);}
function stairLoop(t){if(!runningStairs)return;const dt=Math.min((t-lastStairTime)/1000,.05);lastStairTime=t;timeLeft-=dt*(.17+Math.min(.28,stairScore*.004));if(timeLeft<=0){timeLeft=0;endStairs('시간이 끝났습니다.');drawStairs();return;}particles.forEach(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=160*dt;p.a-=dt*1.8;});particles=particles.filter(p=>p.a>0);updateStairHud();drawStairs();requestAnimationFrame(stairLoop);}
function drawStairs(){const w=stairsCanvas.width,h=stairsCanvas.height;stx.fillStyle='#07101c';stx.fillRect(0,0,w,h);const grd=stx.createLinearGradient(0,0,0,h);grd.addColorStop(0,'#122743');grd.addColorStop(1,'#07101c');stx.fillStyle=grd;stx.fillRect(0,0,w,h);stx.fillStyle='rgba(255,255,255,.55)';for(let i=0;i<45;i++){const x=(i*137)%w,y=(i*83)%h;stx.fillRect(x,y,i%3+1,i%3+1);}const baseX=360,baseY=570,stepW=116,stepH=38;for(let offset=-2;offset<9;offset++){const idx=stepIndex+offset;if(idx<0||idx>=stairPath.length)continue;const rel=stairPath[idx]-stairPath[stepIndex],x=baseX+rel*58-stepW/2,y=baseY-offset*52;stx.fillStyle=idx===stepIndex?'#f0b95b':'#314862';stx.fillRect(x,y,stepW,stepH);stx.fillStyle=idx===stepIndex?'#ffd990':'#4e6987';stx.fillRect(x,y,stepW,8);stx.fillStyle='rgba(0,0,0,.25)';stx.fillRect(x+10,y+14,stepW-20,4);}stx.save();stx.translate(baseX,baseY-34);stx.fillStyle='#72ddff';stx.beginPath();stx.arc(0,-24,13,0,Math.PI*2);stx.fill();stx.fillStyle='#f4f1e8';stx.fillRect(-11,-10,22,31);stx.strokeStyle='#f4f1e8';stx.lineWidth=7;stx.lineCap='round';stx.beginPath();stx.moveTo(-5,18);stx.lineTo(-13,34);stx.moveTo(5,18);stx.lineTo(14,34);stx.stroke();stx.restore();if(runningStairs){const dir=expected();stx.fillStyle='rgba(4,9,16,.78)';stx.beginPath();stx.roundRect(286,105,148,70,14);stx.fill();stx.fillStyle='#ffd990';stx.font='900 38px system-ui';stx.textAlign='center';stx.fillText(dir==='left'?'← 왼쪽':'오른쪽 →',360,152);}particles.forEach(p=>{stx.globalAlpha=Math.max(0,p.a);stx.fillStyle='#ffd990';stx.fillRect(p.x,p.y,5,5);});stx.globalAlpha=1;}
stairsStart.addEventListener('click',startStairs);document.addEventListener('keydown',e=>{const map={ArrowLeft:'left',KeyA:'left',ArrowRight:'right',KeyD:'right'};if(map[e.code]){e.preventDefault();step(map[e.code]);}});document.querySelectorAll('[data-step]').forEach(button=>button.addEventListener('pointerdown',()=>step(button.dataset.step)));stairsBest.textContent=`최고 ${best}`;resetStairs();
