create table if not exists public.rankings (
  id bigint generated by default as identity primary key,
  nickname text not null check (char_length(nickname) between 1 and 12),
  score integer not null check (score between 0 and 1000000),
  level integer not null check (level between 1 and 1000),
  created_at timestamptz not null default now()
);

alter table public.rankings enable row level security;

drop policy if exists "rankings are publicly readable" on public.rankings;
create policy "rankings are publicly readable"
on public.rankings for select
to anon
using (true);

drop policy if exists "anyone can submit a valid score" on public.rankings;
create policy "anyone can submit a valid score"
on public.rankings for insert
to anon
with check (
  char_length(nickname) between 1 and 12
  and score between 0 and 1000000
  and level between 1 and 1000
);

create index if not exists rankings_score_idx
on public.rankings (score desc, created_at asc);
